Closes #1
HimmelSpark/recipista pull request #6
Opened 2020-11-10 19:43 UTC by Neonchick

Добовение списка

2020-11-11 06:34 UTC, HimmelSpark commented on Recipista/.idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
@Neonchick 
Уверен, что файлы из .idea должны быть в репозитории?

2020-11-11 07:16 UTC, HimmelSpark requested changes

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
Версии надо вынести в глобальный build.gradle
В глобальном файле добавляешь следующее:
```
configure(subprojects) { subProject ->
    ext {
        daggerVersion = '2.17'
    }
}
```
А в этом build.gradle импортишь так:
```
implementation group: 'com.google.dagger', name:'dagger', version: daggerVersion
```

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientAdapter.java
> +package ru.mail.hse.recipista;
Запихни в пакет adapter

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientAdapter.java
> +        // Получаем инфлейтер и создаем нужный layout
Комменты не нужны. Только, если что-то нестандартное и неочевидное либо пометка на будущее

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientAdapter.java
> +        // Создаем ViewHolder
См выше

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientAdapter.java
> +    List<String> ingredients;
private

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientFragment.java
> +package ru.mail.hse.recipista;
Запихни в пакет fragment

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientFragment.java
> +    RecyclerView recycler = null;
private

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientViewHolder.java
> +    TextView ingredientTV = itemView.findViewById(R.id.ingredient_tv);
private

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredientViewHolder.java
> +package ru.mail.hse.recipista;
В пакет viewholder

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredinentRepository.java
> +package ru.mail.hse.recipista;
В пакет repository

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredinentRepository.java
> +    public static IngredinentRepository getInstance() {
Если сделать статическую инициализацию списка, то можно не городить синглтон

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredinentRepository.java
> +    // Константы
убери комменты

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/IngredinentRepository.java
> +}
добавь пустую строку в конец

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/MainActivity.java
> +    final String TAG_LIST = "LIST";
Возможно в будущем будем извлекать для чего-то этот ресайклер по этому тегу
Давай сделаем класс со статическими тегами. Мне кажется такое надо выносить в отдельное место.
Что думаешь?

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/MainActivity.java
> +    final String TAG_LIST = "LIST";
private)

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/MainActivity.java
>  }
add newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/res/layout/activity_main.xml
> +    android:id="@+id/main_layout"/>
add newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/res/layout/list_element.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/res/layout/list_fragment.xml
> +</FrameLayout>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/res/values/dimens.xml
> +</resources>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/.idea/gradle.xml
> +</project>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/.idea/codeStyles/codeStyleConfig.xml
> +</component>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/.idea/codeStyles/Project.xml
> +</component>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/.idea/jarRepositories.xml
> +</project>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/.idea/misc.xml
> +</project>
newline

2020-11-11 07:16 UTC, HimmelSpark commented on Recipista/app/src/main/java/ru/mail/hse/recipista/MainActivity.java
>  }
newline

2020-11-11 07:23 UTC, HimmelSpark commented
![](https://github.trello.services/images/mini-trello-icon.png) [Сделать ресайклер](https://trello.com/c/DHhH34k3/1-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C-%D1%80%D0%B5%D1%81%D0%B0%D0%B9%D0%BA%D0%BB%D0%B5%D1%80)

2020-11-11 07:25 UTC, HimmelSpark commented
@Neonchick 
Подтяни в свою ветку актуальный девелоп

2020-11-11 11:52 UTC, Neonchick reviewed
Теперь понял

2020-11-12 21:03 UTC, HimmelSpark approved these changes

2020-11-12 21:04 UTC, merged